### ISSUE TITLE
preprocessing of  CHAOS dataset

### ISSUE THREAD

**Issue by BrunoSauvalle** [WenRuxue/DeTTA#1]
Thanks for sharing the code of your paper.

I have an issue with the preprocessing of the CHAOS dataset as described in your paper and associated code. It is  indicated that it is the same preprocessing as for the LITS dataset and the associated code for reading and processing nii files is provided. However the public repository  for the CHAOS dataset  (https://zenodo.org/records/3431873) provides the data in .dcm (DICOM) format, with a very different data distribution compared to .nii files.

Could you please indicate how the .dcm CHAOS files were processed ? Or where you found the CHAOS .nii files ?

Regards,

**Comment by WenRuxue** [comment]
Thank you for your interest in our work.

We use the original .dcm files that are publicly available on the CHAOS website. In fact, the key processing steps are exactly the same as the .nii file, except for the very first part of reading the file. You can refer to the standard .dcm reading section for more information on how to read the file. We will add the related code later, please stay tuned.

Sincerely,

Ruxue Wen

-----原始邮件-----
发件人:BrunoSauvalle ***@***.***>
发送时间:2023-11-15 22:05:31 (星期三)
收件人: WenRuxue/DeTTA ***@***.***>
抄送: Subscribed ***@***.***>
主题: [WenRuxue/DeTTA] preprocessing of CHAOS dataset (Issue #1)






Thanks for sharing the code of your paper.

I have an issue with the preprocessing of the CHAOS dataset as described in your paper and associated code. It is indicated that it is the same preprocessing as for the LITS dataset and the associated code for reading and processing nii files is provided. However the public repository for the CHAOS dataset (https://zenodo.org/records/3431873) provides the data in .dcm (DICOM) format, with a very different data distribution compared to .nii files.

Could you please indicate how the .dcm CHAOS files were processed ? Or where you found the CHAOS .nii files ?

Regards,

**Comment by WenRuxue** [comment]
I have updated the README.md for this issue.

**Comment by BrunoSauvalle** [comment]
Thanks !
